driver:
  require_chef_omnibus: <%= ENV.fetch("CHEF_VERSION", "latest") %>
  provider: <%= ENV.fetch("CHEF_PROVIDER", "virtualbox") %>
  ssh_key: <%= File.expand_path("./test/support/keys/vagrant") %>
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-6.0.8
  - name: debian-7.2.0
  - name: ubuntu-12.04
  - name: ubuntu-13.10
    attributes:
      postgresql:
        apt_distribution: precise
  - name: ubuntu-14.04


suites:
  - name: server
    run_list:
      - recipe[postgresql::server]
      - recipe[postgresql::client]
      - recipe[postgresql::contrib]
      - recipe[postgresql::dbg]
      - recipe[postgresql::doc]
      - recipe[postgresql::libpq]
      - recipe[postgresql::server_dev]
      - recipe[minitest-handler]
    attributes:
      postgresql:
        users:
          - username: testuser
            password: s3kr1t
            login: true
        databases:
          - name: testdb
            owner: testuser
            template: template0
            encoding: utf8
            locale: en_US.UTF8
            # postgis: true
            extensions:
              - hstore
              - dblink
              - uuid-ossp
            languages:
              - plpgsql
